Organisms/Newsの作成
moe-backend/MOE-frontend-basic-last-assignment pull request #8
Opened 2022-07-23 08:22 UTC by moe-backend

## セルフチェック
- [x] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [x] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [x] 記述の重複はないか

[リンク](http://localhost:6007/?path=/story/organisms-news--news)

2022-07-24 08:28 UTC, Hasegawa62 reviewed
ご確認お願いします！

2022-07-24 08:28 UTC, Hasegawa62 commented on src/components/organisms/news/news.html
> +<article class="article">
articletタグは記事ごとに使いましょう！

2022-07-24 08:28 UTC, Hasegawa62 commented on src/components/organisms/news/news.html
> +      <h5 class="article-date">2018.06.20</h5>
日付はその記事の補足的な情報であり、見出しタグを使うのは適切でないと思います。
日付を表すときに使われるタグがあるので使ってみてください！

2022-07-24 08:28 UTC, Hasegawa62 commented on src/components/organisms/news/news.scss
> +      text-decoration: none;
aタグのtext-decoration:under-line(初期値)が効いていて下線が出ています！
![image](https://user-images.githubusercontent.com/94204610/180638372-d39f332c-f2d4-4b8c-9743-a7a2c45c7b34.png)

2022-07-24 08:28 UTC, Hasegawa62 commented on src/components/organisms/news/news.scss
> +    .article-content {
hover時の色は、organismsの左側にあるmolecules/newsにあります！
![image](https://user-images.githubusercontent.com/94204610/180638844-bcc845fd-adc2-428c-85cc-48c247c0731c.png)

2022-07-25 08:08 UTC, moe-backend commented on src/components/organisms/news/news.scss
> +      text-decoration: none;
aタグの初期値を削除しました。

2022-07-25 08:08 UTC, moe-backend commented on src/components/organisms/news/news.html
> +      <h5 class="article-date">2018.06.20</h5>
timeタグを使いました！paddingの設定がborderを超えてしまうのはなぜでしょうか？

2022-07-25 08:08 UTC, moe-backend commented on src/components/organisms/news/news.scss
> +    .article-content {
ありがとうございます！！

2022-07-26 04:08 UTC, minezaki-mutsuki reviewed
timeタグやarticle-contentのpaddingをarticle-itemで一括で持たせて余白調節したほうがシンプルになります(timeタグのpaddingがはみ出る件についてもtimeタグにpaddingを当てないことになるので一応解決策にはなります)

2022-07-26 04:08 UTC, minezaki-mutsuki commented on src/components/organisms/news/news.html
> +      </p></a
aの閉じタグが途中で改行されているのでインデントとして正しい形に直してください

2022-07-26 04:08 UTC, minezaki-mutsuki commented on src/components/organisms/news/news.scss
> +      font-weight: 400;
ここデフォルトで400だと思います

2022-07-26 04:16 UTC, minezaki-mutsuki commented on src/components/organisms/news/news.html
> +      <h5 class="article-date">2018.06.20</h5>
ごめんなさいpaddingが親要素や兄弟要素を無視して被ってしまう現象についてこの実装でなぜ起こるのか分からなかったです...
二次レビュワーさんに一旦回答を委ねたいです

2022-07-27 05:25 UTC, higashiji2000 commented on src/components/organisms/news/news.html
> +      <h5 class="article-date">2018.06.20</h5>
time要素がデフォルトだと display: inline であることが原因だと思います。
対応としては display に block または inline-block を指定するのが楽かなと思います。

下の記事に似た内容が書いてありますので参考にしてみてください🌴 
https://saruwakakun.com/html-css/basic/display#section3

2022-07-27 14:36 UTC, moe-backend commented on src/components/organisms/news/news.html
> +      <h5 class="article-date">2018.06.20</h5>
解決しました！ありがとうございます。

2022-07-27 14:36 UTC, moe-backend commented on src/components/organisms/news/news.html
> +      </p></a
article-itemにpaddingを付けました！ありがとうございました。

2022-07-28 05:49 UTC, minezaki-mutsuki commented on src/components/organisms/news/news.scss
> +    padding: 20px 26px 20px 20px;
paddingは全て20pxで統一でよいと思います

2022-07-28 05:49 UTC, minezaki-mutsuki commented on src/components/organisms/news/news.scss
> +    time {
timeと.article-contentの間に間隔があるのでそちらを再現してください（この際.article-itemの高さが85pxになるように注意してください！）

2022-07-28 05:49 UTC, minezaki-mutsuki commented on src/components/organisms/news/news.html
> +
HTMLファイルは空行はない方がいいと思います

2022-07-28 12:06 UTC, moe-backend commented on src/components/organisms/news/news.scss
> +    time {
見逃してました。ありがとうございます！
height: 85px; で指定しました。

2022-07-30 03:52 UTC, minezaki-mutsuki commented on src/components/organisms/news/news.scss
> +      padding-bottom: 10px;
兄弟要素との間隔を取る際はmarginの方が適切かと思います

2022-07-30 03:52 UTC, minezaki-mutsuki commented on src/components/organisms/news/news.scss
> +    time {
figmaの文字の高さがデフォルトのものより低い気がするのでline-heightを当てる対応でいいと思います！

2022-07-30 03:52 UTC, minezaki-mutsuki commented on src/components/organisms/news/news.scss
> +    height: 85px;
widthやheightのような指定は基本的にしない方がいいので、timeとarticle-contentの間隔を9pxにする等で高さを調節してもらえればと思います

2022-07-30 03:52 UTC, minezaki-mutsuki commented on src/components/organisms/news/news.html
> +    >お知らせ一覧<i class="fa-solid fa-angle-right"></i
この辺りのタグの位置がずれているので直していただければと思います

2022-08-01 06:23 UTC, moe-backend commented on src/components/organisms/news/news.scss
> +    height: 85px;
承知しました！timeタグにmargin-bottom: 9px;を当てました。

2022-08-01 06:36 UTC, moe-backend commented on src/components/organisms/news/news.scss
> +    time {
承知しました！良かったです！！

2022-08-02 08:33 UTC, KEISUKE0293 reviewed
良いと思います！

2022-08-02 08:33 UTC, KEISUKE0293 commented on src/components/organisms/news/news.scss
> +      margin-bottom: 9px;
figmaで確認したら10pxだったんですけどどちらなんでしょう^^*
もしそちらの方で9pxだったらそのままで大丈夫です！

2022-08-02 11:24 UTC, MoAI522 commented on src/components/organisms/news/news.html
> +    <a href="#">
articleのpaddingの部分でリンクの判定が無くなってしまっていて直観的ではないので、article全体がリンクになるようにしましょう。

2022-08-03 12:51 UTC, moe-backend commented on src/components/organisms/news/news.scss
> +      margin-bottom: 9px;
https://github.com/moe-backend/MOE-frontend-basic-last-assignment/pull/8#discussion_r933726028
ありがとうございます！以前見ていただき、このように9pxにしました。

2022-08-03 13:01 UTC, moe-backend commented on src/components/organisms/news/news.html
> +    <a href="#">
それぞれの記事全体がリンクになるようにしました。ありがとうございました！

2022-08-05 04:16 UTC, MoAI522 commented on src/components/organisms/news/news.html
> +<div class="news-title">
全体をまとめてdivで囲んで、このコンポーネント特有のクラスを付けましょう。

2022-08-05 04:16 UTC, MoAI522 commented on src/components/organisms/news/news.scss
> +.article {
htmlの方で指定したコンポーネント全体のクラスを用いて、このコンポーネント内でのみスタイルが適用されるようにしましょう。

2022-08-08 03:53 UTC, haruchu reviewed
コメントしました

2022-08-08 03:53 UTC, haruchu commented on src/components/organisms/news/news.scss
> +      border: 1px solid $gray_gainsboro;
article同士のborderが重なっています
少し工夫してみてborderが重ならないようにしてみましょう！
<img width="784" alt="スクリーンショット 2022-08-08 12 51 29" src="https://user-images.githubusercontent.com/66406382/183335512-4c1f0712-56e0-4574-a178-ecdb218df04f.png">

2022-08-08 12:08 UTC, moe-backend commented on src/components/organisms/news/news.scss
> +      border: 1px solid $gray_gainsboro;
last-childではなく新たにクラス名を付けて修正しました！ありがとうございます！！

2022-08-09 07:36 UTC, haruchu reviewed
コメントしました

2022-08-09 07:36 UTC, haruchu commented on src/components/organisms/news/news.html
> +      <article class="article-item article-item-last">
クラス名をつけるのではなく、last-childを用いた方法のままでやってみて欲しいです！
以前のやり方ではlast-childが思うように動作していなかったと思うので、もう一度考えてみてください
ちなみに、前回は各記事にlast-childが適応されてしまっていました

2022-08-09 09:08 UTC, moe-backend commented on src/components/organisms/news/news.html
> +      <article class="article-item article-item-last">
承知しました！aタグの方にlast-childを指定することで解決できました。

2022-08-12 11:44 UTC, higashiji2000 approved these changes
![image](https://user-images.githubusercontent.com/83479175/184347281-1e0b60a3-fb0d-45ab-ab5d-d409652397cf.png)
news-and-events-more を ホバー時に下線が出てしまっているので、修正をお願いします。
このPRで対応するので問題ないと思います！

2022-08-12 11:44 UTC, higashiji2000 commented on src/components/organisms/news/news.scss
> +  .news-and-events-more-parent {
こういう感じの、既存コンポーネントを囲む部品を wrap とか wrapper とか命名したりすることが多い気がするので参考にしてみてください

2022-08-12 11:44 UTC, higashiji2000 commented on src/components/organisms/news/news.html
> +        <time>2018.06.08</time>
time タグには datetime属性を設定することになっているので、目を通してみてください(最終課題では見た目があってれば問題ないという方針なのでそこまで厳密でなくても大丈夫です。)
mdn: https://developer.mozilla.org/ja/docs/Web/HTML/Element/time

2022-08-12 11:46 UTC, higashiji2000 requested changes
間違えてapproveしました 🙏 
news-and-events-moreの修正だけお願いします！

2022-08-13 00:34 UTC, moe-backend commented on src/components/organisms/news/news.scss
> +  .news-and-events-more-parent {
そちらに変更します！！

2022-08-13 01:16 UTC, moe-backend commented on src/components/organisms/news/news.html
> +        <time>2018.06.08</time>
ありがとうございます！！確認してdatetme属性を追加しました。

2022-08-14 02:59 UTC, higashiji2000 requested changes
対応ありがとうございます！
news-and-events-moreの修正だけできていないようなのでお手数ですがそこだけお願いします。

2022-08-14 15:34 UTC, higashiji2000 commented
![image](https://user-images.githubusercontent.com/83479175/184544026-19655c30-3dd7-4fb9-91bb-f191b6c81210.png)

おそらく #16 で下線削除の対応をしていただいたと思うのですが、こちらでの対応に問題があるみたいです…！

![image](https://user-images.githubusercontent.com/83479175/184544079-50de2dc3-3b4d-458b-90d2-a5de0b2bef66.png)

> CSS のルールでは、[直接対象となった要素](https://developer.mozilla.org/ja/docs/Web/CSS/Specificity#%E7%9B%B4%E6%8E%A5%E5%AF%BE%E8%B1%A1%E3%81%AE%E8%A6%81%E7%B4%A0%E3%81%A8%E7%B6%99%E6%89%BF%E3%81%95%E3%82%8C%E3%81%9F%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB)は要素が祖先から継承したルールよりも常に優先されます。

という仕様があるので、a:hover は クラスセレクタより詳細度が低いにもかかわらず 優先して適用されてしまうという感じです。このPR内で修正をお願いしたいです 🙏 
ペース良く進めていただいているのにやり取りが多くなってしまい申し訳ないです 🙇 

どの宣言が優先されるかの挙動についての参考： https://developer.mozilla.org/ja/docs/Web/CSS/Specificity

2022-08-15 06:09 UTC, higashiji2000 approved these changes
LGTMです！
修正PRも基本的にレビュー依頼お願いします:pray:

2022-08-15 06:30 UTC, merged